const cardArray = [
    { name: "home", icon: "fa-solid fa-house" },
    { name: "user", icon: "fa-solid fa-user" },
    { name: "settings", icon: "fa-solid fa-gear" },
    { name: "messages", icon: "fa-solid fa-envelope" },
    { name: "notifications", icon: "fa-solid fa-bell" },
    { name: "search", icon: "fa-solid fa-magnifying-glass" },
    { name: "camera", icon: "fa-solid fa-camera" },
    { name: "calendar", icon: "fa-solid fa-calendar-days" },
    { name: "music", icon: "fa-solid fa-music" },
    { name: "video", icon: "fa-solid fa-video" },
    { name: "chat", icon: "fa-solid fa-comments" },
    { name: "download", icon: "fa-solid fa-download" },
    { name: "upload", icon: "fa-solid fa-upload" },
    { name: "file", icon: "fa-solid fa-file" },
    { name: "folder", icon: "fa-solid fa-folder" },
    { name: "lock", icon: "fa-solid fa-lock" },
    { name: "unlock", icon: "fa-solid fa-lock-open" },
    { name: "map", icon: "fa-solid fa-map" },
    { name: "location", icon: "fa-solid fa-location-dot" },
    { name: "bookmark", icon: "fa-solid fa-bookmark" },
    { name: "star", icon: "fa-solid fa-star" },
    { name: "heart", icon: "fa-solid fa-heart" },
    { name: "phone", icon: "fa-solid fa-phone" },
    { name: "globe", icon: "fa-solid fa-globe" },
    { name: "shopping", icon: "fa-solid fa-cart-shopping" },
    { name: "wallet", icon: "fa-solid fa-wallet" },
    { name: "credit card", icon: "fa-solid fa-credit-card" },
    { name: "trash", icon: "fa-solid fa-trash" },
    { name: "edit", icon: "fa-solid fa-pen" },
    { name: "plus", icon: "fa-solid fa-plus" },
    { name: "minus", icon: "fa-solid fa-minus" },
    { name: "info", icon: "fa-solid fa-circle-info" },
    { name: "help", icon: "fa-solid fa-circle-question" },
    { name: "download cloud", icon: "fa-solid fa-cloud-arrow-down" },
    { name: "upload cloud", icon: "fa-solid fa-cloud-arrow-up" }
];
